package project.models.entity.enums;

public enum CityNameEnum {
    BLAGOEVGRAD, BURGAS, VARNA, VELIKO_TARNOVO, VIDIN, VRACA, GABROVO, DOBRICH, KARDZHALI, KUSTENDIL, LOVECH,
    MONTANA, PAZARDZHIK, PERNIK, PLEVEN, PLOVDIV, RAZGRAD, RUSE, SISLISTRA, SLIVEN, SMOLYAN, SOFIA, STARA_ZAGORA,
    TARGOVISHTE, HASKOVO, SHUMEN, YAMBOL;


    }
